# If there are words that you think should not be treated as typo.
# Please list here along with a comment.
[default.extend-words]
"MUTLI" = "MUTLI"
"SPLITTED" = "SPLITTED"
"ba" = "ba"
"hel" = "hel"

[files]
extend-exclude = ["docs/api/*"]
